## Python practice  3

In [24]:
string ='HACK'
n = 2   # pair
from itertools import permutations
def fun1(string,n):
    inpA =[]
    for s in string:
        inpA.append(s)
# inpA = lt
    r =len(inpA)
    lt2 = list(permutations(inpA,n))
# print(lt2)
    for i in (sorted(lt2)):
        print((''.join(i))) 
    return

In [16]:

for i in (sorted(lt2)):
    print((''.join(i))) 

AC
AH
AK
CA
CH
CK
HA
HC
HK
KA
KC
KH


In [29]:
from itertools import permutations
def fun1(string,n):
    inpA =[]
    for s in string:
        inpA.append(s)
# inpA = lt
    r =len(inpA)
    lt2 = list(permutations(inpA,n))
# print(lt2)
    for i in (sorted(lt2)):
        x =''.join(i) 
    return x
if '__name__'=='__main__':
    string = input()
    n =int(input())
    result = fun1(string,n)
    print(result)

In [1]:
from itertools import combinations
# string,n=input().split()
string ='HAKE'
n = 2
k= int(n)
for i in range (1,k+1):
    for j in combinations(sorted(string),i):
        print(''.join(j))

A
E
H
K
AE
AH
AK
EH
EK
HK


In [73]:
from itertools import combinations_with_replacement
# string,n = input().split()
# k=int(n)
string ='HACK'
k= 2
st1 =(list(combinations_with_replacement(sorted(string),k)))
for i in st1:
    print(''.join(i))

AA
AC
AH
AK
CC
CH
CK
HH
HK
KK


In [1]:
from itertools import permutations
string = '1222311'
lt = sorted(list(permutations(string,2)))

lt1=[]
for i in lt:
    if i not in lt1:
        lt1.append(i)
for i in lt1:
    print(i,end =' ')

('1', '1') ('1', '2') ('1', '3') ('2', '1') ('2', '2') ('2', '3') ('3', '1') ('3', '2') 

In [33]:

from collections import Counter

In [31]:
n =int(input())
store = input().split()


10
2 3 4 5 6 8 7 6 5 18


In [60]:
# print(store)
lt = []
for i in store:
    lt.append(int(i))
# print(dict(Counter(lt)))
count_store = dict(Counter(lt))
sho_siz = count_store.keys() 
num_sho = count_store.values()
print(sho_siz)

dict_keys([2, 3, 4, 5, 6, 8, 7, 18])


In [69]:
size_cust = [2 ,4,7,5,18]
lt2 = list(sho_siz)
for i in lt2:
    for j in size_cust:
        if j==i:
            num =count_store.get(j)
            print(num)

1
1
2
1
1


2


In [30]:
for i in string :
    for j in size_cust:
        if j ==i:
            print(None)
    print('customer will pay')

None
customer will pay
None
customer will pay
None
customer will pay
None
customer will pay


In [100]:
n =4#input()
lt =[]
for i in range (n):
    x = input()
    lt.append(x)

    

bcdef
abcdefg
bcde
bcdef


In [101]:
st = ' '.join(lt)
print(st)

bcdef abcdefg bcde bcdef


In [104]:
for s in lt:
    print (st.count(s), end = '')


3143

In [93]:
import re

word = "dog"
str = "the dogs barked"
print (len(re.findall(word, str)))

1


In [137]:
import calendar
month,day,year =map(int,input().split())
day_list = ['MONDAY ', 'TUESDAY' ,'WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY']

num_day = calendar.weekday(year,month,day)
print(day_list[num_day])

11 18 1955
FRIDAY


In [123]:
day_list[num_day]

'Thursday'

In [142]:
#Code
try:
    print(1/0)
except ZeroDivisionError as e:
    print ("Error Code:",e)

Error Code: division by zero


In [152]:
lt = [0,2, 1]
for i in range(3):
    for j in lt:
        try:
            print(i/j)
        except ZeroDivisionError as e:
            print('Error Code:',e)

Error Code: division by zero
0.0
0.0
Error Code: division by zero
0.5
1.0
Error Code: division by zero
1.0
2.0


In [ ]:
import re 
T =int(input())
for i in range(T):
    try :
        re.compile(input())
        print(True)
    except :
        print(False)

In [2]:
import numpy as np
pl_lt = list(map(float, input().split()))
x =int(input())
print(np.polyval(pl_lt,x))

2
2
2.0


In [30]:
dim = int(input())
row1 = list(map(float,input().split()))
row2 = list(map(float,input().split()))
row1.extend(row2)
m1 = np.asarray(row1)
m2 = np.reshape(m1,(dim,dim))
np.linalg.det(m2,dim)

KeyboardInterrupt: Interrupted by user

In [40]:
lt =[]
N = int(input())
for i in range (N):
    lt.append(list(map(float,input().split())))
print(round(np.linalg.det(lt),2))

2
1 2
2 3
-1.0


In [64]:
lt0 =[]
lt1 = ['v','Y','o','M','4','3']
for  i in range (len(lt1)):
    if lt1[i].islower()== True:
        lt0.append(lt1[i])
    else :
        if lt1[i].isupper() ==True:
            lt0.append(lt1[i])
        else:
            if lt1[i].isdigit()==True and int(i)%2 !=0:
                lt0.append(lt1[i])
            else :
                if lt1[i].isdigit()==True and int(i)%2 ==0:
                    lt0.append(lt1[i])
#         break
        
    

In [75]:
stg= 'Sorting1234'
lt2 =[]
for s in stg:
    lt2.append(s)
print(lt2)

['S', 'o', 'r', 't', 'i', 'n', 'g', '1', '2', '3', '4']


In [27]:
lt11 =[]
lt22 =[]
lt33 =[]
lt44 =[]
lt1 = []

lt =list(input().split())
for s in str(lt):
    lt1.append(s)

# lt1 = lt2#['v','Y','o','M','4','3']
for  i in range (len(lt1)):
    if lt1[i].islower()== True:
        lt11.append(lt1[i])
    elif lt1[i].isupper() ==True:
        lt22.append(lt1[i])
    elif lt1[i].isdigit()==True and int(i)%2 !=0:
        lt33.append(lt1[i])
    elif lt1[i].isdigit()==True and int(i)%2 ==0:
        lt44.append(lt1[i])
out = sorted(lt11)+sorted(lt22)+lt33+lt44
print(''.join(out))

Sorting1234
ginortS1324


In [145]:
print(lt1)

['Sorting1234']


['o', 'r', 't', 'i', 'n', 'g', 'S', '1', '3', '2', '4']

In [111]:
lst

[['o', 'r', 't', 'i', 'n', 'g'], ['S'], ['1', '3'], ['2', '4']]

In [29]:
# from __future__ import print_function

upper = []
lower = []
even = []
odd = []
lt1 = []
lt =list(input().split())
for s in str(lt):
    lt1.append(s)

for  i in range (len(lt1)):
    a = lt1[i]
    
    if lt1[i].islower()== True:
        lower.append(lt1[i])
    elif lt1[i].isupper() ==True:
        upper.append(lt1[i])
    elif lt1[i].isdigit()==True and int(i)%2 ==0:
        even.append(lt1[i])
    elif lt1[i].isdigit()==True and int(i)%2 !=0:
        odd.append(lt1[i])
   

## upper.sort()
lower.sort()
even.sort()
odd.sort()

t = lower+upper+odd+even
print(''.join(t))


Sorting1234
ginortS1324


In [16]:
lt1


['[', "'", 'a', 's', 'd', 'a', 's', 'd', '4', '5', "'", ']']

### Practice of Sets 1

In [34]:

def average(array):
    avg = sum(list(set(array)))/len(set(array))
    result= round(avg,3)
    return result
if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

10
161 182 161 154 176 170 167 171 170 174
169.375


### Set Practice 2

In [75]:
N= int(input())
set1 =  set(map(int,input().split()))
M= int(input())
set2 =  set(map(int,input().split()))
if (set1.intersection(set2)==set2.intersection(set1) )==True:
    out1 = set1.intersection(set2)
    out2 = set1.union(set2)
    uni= sorted(list(out2.difference(out1)))

for i in uni:
    print(i)


4
2 4 5 9
4
12 15 5 9
5
9
12
15


In [83]:
n = int(input())
s = set(map(int,input().split()))
num =int(input())
for i in range(num):
    ip = input().split()
    if ip[0]=="remove":
        s.remove(int(ip[1]))
    elif ip[0]=="discard":
        s.discard(int(ip[1]))
    else :
        s.pop()
print(sum(list(s)))
    
        

9
1 2 3 4 5 6 7 8 9
10
remove 9
discard 9 
dicard 8
remove 7
pop
dicard 6
remove 5
pop
discard 5
pop
8


In [98]:
N = int(input('Total number of country:' ))
empty = set()
for i in range (N):
    set_1 = input('Pls Enter the Name of Contry :')
    empty.add(set_1)
print(len(empty))

Total number of country:7
Pls Enter thr Name of Contry :UK
Pls Enter thr Name of Contry :CHINA
Pls Enter thr Name of Contry :USA
Pls Enter thr Name of Contry :FRANCE
Pls Enter thr Name of Contry :NEW LAND
Pls Enter thr Name of Contry :UK
Pls Enter thr Name of Contry :FRANCE
5


In [167]:
N1 = int(input())
set1 = set()
inp1 = list(input().split())

N2 = int(input())
set2 = []
inp = list(input().split())

inp1.extend(inp)
len(set(inp1) )


2
1 2 
5
1 2 11 12 13


In [161]:
inp1.extend(inp)

In [164]:
len(set(inp1) )

3

In [5]:
N1 = int(input())
set1 = set()
inp1 = list(input().split())

N2 = int(input())
set2 = []
inp = list(input().split())
NUm_st_only_Eng = set(inp1).difference(set(inp))
print(len(NUm_st_only_Eng))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


In [6]:
NUm_st_only_Eng

{'4', '5', '7', '9'}

{'c', 'R', 'H', 'n', 'r', 'e'}


### .symmetric_difference() operator  or (set1)^(set2) 

In [9]:
s = set("Hacker")
print(s.symmetric_difference("Rank"))

{'c', 'R', 'H', 'n', 'r', 'e'}


In [15]:
s1 =set('Vyom' )
s2 = set('Kumar')
print(s1.symmetric_difference(s2) )

{'o', 'a', 'r', 'u', 'K', 'y', 'V'}


In [22]:
s = set("Hacker")
print(s)
print(s.symmetric_difference(set(['R', 'a', 'n', 'k'])) )

{'c', 'H', 'k', 'a', 'r', 'e'}
{'c', 'R', 'H', 'n', 'r', 'e'}


In [23]:
lst = ['R', 'a', 'n', 'k']
print(s.symmetric_difference(['R', 'a', 'n', 'k']) )

{'c', 'R', 'H', 'n', 'r', 'e'}


In [24]:
N1 = int(input())
set1 = set()
inp1 = list(input().split())

N2 = int(input())
set2 = []
inp = list(input().split())
NUm_st_only_Eng = set(inp1).difference(set(inp))
print(len(NUm_st_only_Eng))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
8


In [33]:
len_set = int(input())

storage = set(map(int, input().split()))

op_len = int(input())

for i in range(op_len):
    operation = input().split()
    if operation[0] == 'intersection_update':
        temp_storage = set(map(int, input().split()))
        storage.intersection_update(temp_storage)
    elif operation[0] == 'update':
        temp_storage = set(map(int, input().split()))
        storage.update(temp_storage)
    elif operation[0] == 'symmetric_difference_update':
        temp_storage = set(map(int, input().split()))
        storage.symmetric_difference_update(temp_storage)
    elif operation[0] == 'difference_update':
        temp_storage = set(map(int, input().split()))
        storage.difference_update(temp_storage)
    else :
        assert False

print(sum(storage))

16
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
4
 intersection_update 10
 2 3 5 6 8 9 1 4 7 11
 update 2
 55 66
 symmetric_difference_update 5
 22 7 35 62 58
177


## .issubset() testing

In [37]:
Num_test = int(input())
for i in range(Num_test):
    NA = int(input())
    setA = set(map(int,input().split()))
    NB = int(input())
    setB = set(map(int,input().split()))
    if setA.issubset(setB):
        print(True)
    else:
        print(False)
    

3
5
1 2 3 5 6
9
9 8 5 6 3 2 1 4 7
True
1
2
5
3 6 5 4 1
False
7
1 2 3 5 6 8 9
3
9 8 2
False


In [60]:
set1 = set(map(int,input().split()))
Num_sub = int(input())
lt = set()
for i in range (Num_sub):
    lt.update(set(map(int,input().split())))

if set1.issuperset(lt):
    print(True)
else:
    print(False)

1 3 4
1
1 3 
True


In [97]:
Num_inp = int(input())
lt = []
for i in range (Num_inp):
    lt.append((input().split()))
       

2
9670962535
2596709625


In [137]:
lt = []
N = int(input())
for i in range(N):
    lt.append('1'*(i+1))
for i in lt:
    print(int(i)**2)

5
1
121
12321
1234321
123454321


In [153]:
lt = []
for i in range(int(input())): #More than 2 lines will result in 0 score. Do not leave a blank line also
    lt.append('1'*(i+1))
for i in lt:
    print(int(i)**2)

5
1
121
12321
1234321
123454321


In [164]:
g = [i for i in range(int(input()))  j for j in lt ]
print(g)

SyntaxError: invalid syntax (986118135.py, line 1)

In [168]:
a = int(input())
b = int(input())
print(a//b)
print(a%b)
print(divmod(a,b))

177
10
17
7
(17, 7)


In [179]:
a = float(input())
b = float(input())
m = int(input())
print(int(pow(a,b)))
print(pow(int(a),int(b),m))

3
4
5
81
1


In [191]:
for i in range(1,int(input())): #More than 2 lines will result in 0 score. Do not leave a blank line also
    prt = int(i*10**i/9)
    print(prt)

5
1
22
333
4444


In [201]:
x, y = input("Enter two values: ").split()

Enter two values: 3 3


In [206]:
import numpy as np

N,M = input().split()
# M = int(input())
np.eye(int(N),int(M),k=0)

3 3


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [215]:

M ,N = input().split()
M1 = np.array(input().split(),float)
M2 = np.array(input().split(),float)

print(np.add(M1,M2))
print(np.subtract(M1,M2))
print(np.multiply(M1,M2))
print(np.divide(M1,M2))
print(np.mod(M1,M2))
print(np.power(M1,M2))

1 4
1 2 3 4
5 6 7 8
[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[1. 2. 3. 4.]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [238]:
M ,N = map(int,input().split())
M1 = np.array(input().split(),float)
M2 = np.array(input().split(),float)

print((np.add(M1,M2)).reshape(M,N).astype(int))
print((np.subtract(M1,M2)).reshape(M,N).astype(int))
print((np.multiply(M1,M2)).reshape(M,N).astype(int))
print(((M1//M2)).reshape(M,N).astype(int))
print((np.mod(M1,M2)).reshape(M,N).astype(int))
print((np.power(M1,M2)).reshape(M,N).astype(int))


KeyboardInterrupt: Interrupted by user

In [233]:
import numpy

N, M = map(int, input().split())

A = numpy.array([list(map(int, input().split())) for n in range(N)])
B = numpy.array([list(map(int, input().split())) for n in range(N)])

print(A + B)
print(A - B)
print(A * B)
print(A // B)
print(A % B)
print(A ** B)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [244]:
arr = np.array(list(map(float,input().split())))
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [ ]:
M,N = list(map(int,input().split()))
Arr = np.array(list(map(int,input().split()))).reshape(M,N)
Arr

In [278]:
import numpy as np
M,N = list(map(int,input().split()))
lt = []
for i in range (M):
    Mi = numpy.array([list(map(int, input().split()))])
    lt.append(Mi)
st = sum(lt)
print(np.prod(st))     

4 4
1 2 1 1
1 2 1 1
1 2 1 1
1 2 1 1
512


In [323]:
lt =[]
M,N = list(map(int,input().split()))
for i in range (M):
    lt.append(min(np.array(list(map(int,input().split())))))
print(max(lt))

2 2
1 2
3 4
2.0


In [335]:
lt =[]
M,N = list(map(int,input().split()))
for i in range (M):
    lt.append(np.array(list(map(int,input().split()))))
    np.array(lt)
print(np.mean(lt,axis= 1))
print(np.var(lt,axis= 0))
print(round(np.std(lt,axis= None),11))

2 2
1 2
 3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


In [356]:
N =int(input())
A =[]
B =[]
for i in range (N):
    A.append(np.array(list(map(int,input().split()))))
for i in range (N):
    B.append(np.array(list(map(int,input().split()))))
print(np.dot(A,B))

2
1 2
3 4
1 2
3 4


In [363]:
A =np.array(list(map(int,input().split())))
B =np.array(list(map(int,input().split())))
print(np.inner(A,B) )
print(np.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]


In [14]:
import numpy

def arrays(arr):
    lst =list(map(int,arr))
    lst.reverse()
    result = numpy.array(lst,float)
    return result
arr = input().strip().split(' ')
result = arrays(arr)
print( result )

1 2 35 6 6 5 4 5 4 6 4 6 4 6 4 
[ 4.  6.  4.  6.  4.  6.  4.  5.  4.  5.  6.  6. 35.  2.  1.]


In [34]:
arr= np.array(list(map(int,input().split())))
print(np.reshape(arr,(3,3)))            

1 2 3 4 5 6 7 8 9 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
lt =[]
N,M= map(int,input().split())
for i in range (N):
    y =list(map(int,input().split()))
    lt.append(y)
    yy = np.array(lt)
print(yy.transpose())
print(yy.flatten())
    
    

2 2
1 2
5 6
[[1 5]
 [2 6]]
[1 2 5 6]


In [74]:
lt =[]
N,M,P= map(int,input().split())
for i in range (N):
    y =list(map(int,input().split()))
    lt.append(y)
    y1 = np.array(lt)
arr1 = np.reshape(y1,(N,P))
lt =[]
for i in range (M):
    y0 =list(map(int,input().split()))
    lt.append(y0)
    y2 = np.array(lt)
arr2 = np.reshape(y2,(M,P))

print(np.concatenate( (arr1,arr2 ),axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4


In [93]:
TP =tuple(map(int,input().split()))
print(np.zeros((TP),dtype = int))
print(np.ones((TP),dtype = int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Pulynomial as input 

In [100]:
fx = input("Enter a Polynomial: ")
x = float(input("At wich position should the polynomial be evaluated: "))

print(eval(fx.replace('x', str(x))))


# Out put -
# Enter a Polynomial: x**3 + x**2 + x + 1
# At wich position should the polynomial be evaluated: 4
# 85.0

Enter a Polynomial: x**3 + x**2 + x + 1
At wich position should the polynomial be evaluated: 4
85.0


In [101]:
x,k = map(int,input().split())
fx = input("Enter a Polynomial: ")
if  eval(fx.replace('x', str(x))) == k:
    print(True)
else:
    print(False)
# 1 4
# Enter a Polynomial: x**3 + x**2 + x + 1
# True

1 4
Enter a Polynomial: x**3 + x**2 + x + 1
True


### mathematics + string Computationals 

In [104]:
var  =input()
eval(var)
#  input is  :print(2 + 3) or 2 + 3

# output is  : 5

2 + 5


7

In [153]:
N = int(input())
string = input()
lst = list(map(int,string.split()))
def palindrom(lst):
    for i in range (N):
        rev = ''.join(reversed(str(lst[i])))
        if ( lst[i] >0 ) and (str(lst[i]) ==(rev)) :
            ans ='x'

    if ans =='x' :
        print(True)
    else :
        print(False)
    
    return

palindrom(lst)


5
12 9 61 5 14
True
None


In [163]:
N = int(input())
string = input()
# lst = list(map(int,string.split()))
rev = ''.join(reversed(str(string)))
if (all(string)>0 and all(string)==rev):
    

SyntaxError: incomplete input (3679367823.py, line 6)

In [170]:
N =int(input())
string =input()
for i in string :
    rev =''.join(reversed(i))
    if all(string) >0 and all(string) ==rev:
        print(True)

2
151 12


In [171]:
print(rev)

2


In [ ]:
N = int(input())
string = input()
lst = list(map(int,string.split()))
def palindrom(lst):
    for i in range (N):
        rev = ''.join(reversed(str(lst[i])))
        if ( lst[i] >0 ) and (str(lst[i]) ==(rev)) :
            ans ='x'

    if ans =='x' :
        print(True)
    else :
        print(False)
    
    return

palindrom(lst)


In [174]:
from scipy.linalg import expm
expm(np.zeros((2,2)))

array([[1., 0.],
       [0., 1.]])

In [194]:
M = 1.0e+11 *np.array( [[2.6847  , 1.0440   , 1.0440 ,        0 ,        0 ,        0],
                    [1.0440  , 2.6847   , 1.0440 ,        0 ,        0 ,        0],
                    [1.0440  , 1.0440   , 2.6847 ,        0 ,        0 ,        0],
                    [     0  ,      0   ,      0 ,   0.8203 ,        0 ,        0],
                    [     0  ,      0   ,      0 ,        0 ,   0.8203 ,        0],
                    [     0  ,      0   ,      0 ,        0 ,        0 ,   0.8203] ])
expm(M)

array([[nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan]])

In [178]:
(np.zeros((2,2)))

array([[0., 0.],
       [0., 0.]])

In [199]:
import numpy as np

a = np.array([ 1.97635114,  1.72790352,  1.51046621,  1.25543557,  1.01718594,
               0.77378732,  0.53452001,  0.29627038,  0.05802074, -0.18022889,
              -0.41847852] ,dtype= complex)
e = -1.377404416

complexAnswer = e**M
realAnswer = complexAnswer.real

C:\Users\HP\AppData\Local\Temp\ipykernel_156668\2948774439.py:8: RuntimeWarning: overflow encountered in power
  complexAnswer = e**M


In [198]:
realAnswer

array([ 1.87773626,  1.14136618,  0.05332228, -1.03877969, -1.38298691,
       -0.97102617, -0.12844   ,  0.65665457,  1.00187468,  0.79661763,
        0.22154892])

## Python Object oriented Programmimg

In [11]:
class student():
    def cheack_pass_fail(self) :
        if self.marks >= 40 :
            return True
        else:
            return False
# object 1
student1 = student()
student1.name = 'Rudra'
student1.marks = 85 
# object 2
student2 = student()
student2.name = 'Arohi'
student2.marks = 35 



print(student1.cheack_pass_fail() )
print(student2.cheack_pass_fail() )

True
False


In [16]:
class student():
    def cheack_pass_fail(self) :
        if self.marks >= 40 :
            return True
        else:
            return False
    def __init__(self,name,mark) :
        self.name = name
        self.mark = mark
        
student1 = student('Rudra', 85)
print(student1.name , student1.mark)
student1 = student('Nisah', 30)
print(student1.name , student1.mark)

Rudra 85
Nisah 30


In [19]:
def odd_even(n):
    if n%2 == 0 and(n>=2 and n<=5) :
        print('Not Weird')
    elif n%2 == 0 and(n>=6 and n<=20) :
        print('Weird')
    elif n%2 == 0 and n>20 :
        print('Not Weird')
    else :
        print('Weird')
odd_even(3)

Weird


In [36]:
def arthematic(a,b):
    sumation  = a+b 
    substraction = a-b 
    multiplication = a*b
    print(sumation )
    print(substraction )
    print(multiplication )
    return  


In [37]:
arthematic(4,5)

9
-1
20


In [39]:
def division(a,b):
    int_div  = a//b 
    float_div = a/b 
    print(int_div )
    print(float_div )
    return  
division(a,b)

In [41]:
division(3,5)

0
0.6


In [44]:
def loop(n):
    if n>0:
        for i in range  (n):
            print(i**2)
loop(n)

0
1
4


In [ ]:
def is_leap(year):
    leap = False
    
    # Write your logic here
    
    return leap

In [98]:
def is_leap(year):
    if (year%4==0 and year%400 == 0) :
        leap = True
    elif year%100 == 0:
        leap = False
    return leap
is_leap(2500)

False

In [161]:
x,y,z,n = 1,1,1,2
def itration(x,y,z,n) :
    list_1 = [x,y,z]
    list2 =[]
    for i in range (x+1):
        for j in range (y+1):
            for k in range (z+1):
                if i+j+k !=2 :
                    list2.append([i,j,k])
    return list2   
itration(x,y,z,n)

In [162]:
itration(x,y,z,n)

[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]

In [154]:
len([[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 2], [0, 2, 1], [0, 2, 2], [1, 0, 0], [1, 0, 2], [1, 1, 1], [1, 1, 2], [1, 2, 0], [1, 2, 1], [1, 2, 2], [2, 0, 1], [2, 0, 2], [2, 1, 0], [2, 1, 1], [2, 1, 2], [2, 2, 0], [2, 2, 1], [2, 2, 2]])

21

In [168]:
x = int(input())
y = int(input())
z = int(input())
n = int(input())
def itration(x,y,z,n) :
    list2 =[]
    
    for i in range (x+1):
        for j in range (y+1):
            for k in range (z+1):
                if x+y+z !=n:
                    list2.append([i,j,k])
    return list2   
itration(x,y,z,n)     

1
2
2
3


[[0, 0, 0],
 [0, 0, 1],
 [0, 0, 2],
 [0, 1, 0],
 [0, 1, 1],
 [0, 1, 2],
 [0, 2, 0],
 [0, 2, 1],
 [0, 2, 2],
 [1, 0, 0],
 [1, 0, 1],
 [1, 0, 2],
 [1, 1, 0],
 [1, 1, 1],
 [1, 1, 2],
 [1, 2, 0],
 [1, 2, 1],
 [1, 2, 2]]